### ISSUE TITLE
Will not install.

### ISSUE THREAD

**Issue by BrendoDerf** [NyarchLinux/NyarchLinux#12]
I have been using rufus to image my usb drive and I get to the boot menu but when pressing enter on the first option it goes blank for a second and then comes back. Pressing enter again causes it to go to a screen saying Error: You need to load the kernel first. 
I have looked this up but found nothing that I can apply to my situation. If someone could please help I would appreciate.

**Comment by BrendoDerf** [comment]
Well turns out secure boot was enabled. I havent tested installing yet after disabling it but about to

**Comment by FrancescoCaracciolo** [comment]
Disabling secure boot may solve the issue. On some devices Nyarch just doesn't work with dual boot
