### ISSUE TITLE
Calamares Install error

### ISSUE THREAD

**Issue by nekolifestyle** [NyarchLinux/NyarchLinux#15]
=== START CALAMARES 3.2.61-1
2023-08-01 - 18:45:32 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "Failed to unpack image \"/run/archiso/bootmnt/arch/x86_64/airootfs.sfs\""

**Comment by FrancescoCaracciolo** [comment]
When does this error occour? And on nvidia ISO or normal?

**Comment by nekolifestyle** [comment]
normal iso

**Comment by nekolifestyle** [comment]
Error occurs at the end of the install process

**Comment by FrancescoCaracciolo** [comment]
Try installing an older version, you can find them on SourceForge or Telegram
