### ISSUE TITLE
Settings resseting after restart

### ISSUE THREAD

**Issue by TheDogHusky** [NyarchLinux/NyarchLinux#24]
Hello Nyarch community.
I've been a neko fan for a long time now. I came accros NyarchLinux on Google and as a Windows user, wanted just to have a VM of it for fun, playing around with it. However, I've been experiencing an issue:
Each time I restart the VM, all the settings (and some data) gets reset, just like if I were reinstalling it each times.
The main user (by default, live password live), that I've modified to Adam with a new password, the keyboard layout that I've set to French, the updates I did, all reset back to default.

And there are been some other issues:
1/2 times I start the VM, the display is f*cked up, loading to it just switching sides, glitching out randomly each times a display update happens (mouse moving, keyboard typing, etc..).
When I log out from an user, it just brings me to this blank terminal page, without doing anything:
![image](https://github.com/NyarchLinux/NyarchLinux/assets/74465875/88bbd8a2-a677-4ceb-8e88-c4994f4fed09)

I saw that each time I restart it, it launches the install script: 
![image](https://github.com/NyarchLinux/NyarchLinux/assets/74465875/d26fc298-d1f1-4b80-be79-a173e83ff1d1)
And one line says something like "finished creating system users".

I guess just Nyarch aint meant to be ran in a VM, but it would be cooler for me if I could just use it that way instead of dual booting or using it as primary OS.

**Comment by TheDogHusky** [comment]
Also, after each restart I get this prompted with the default system user:
![image](https://github.com/NyarchLinux/NyarchLinux/assets/74465875/7e74b6bd-b920-4c0a-a1ba-bdb6eda71c83)
(as for that example my whole screen was not working: mouse moving, changing, button animations but clicking anywhere wont do anything, same for keyboard)

**Comment by FrancescoCaracciolo** [comment]
Hello, you have not installed Nyarch, this is just the live user. In the dock there is an icon to start the installer for the system

**Comment by TheDogHusky** [comment]
Oh yeah sorry, didn't saw that.

**Comment by TheDogHusky** [comment]
I guess that issue is solved

**Comment by FrancescoCaracciolo** [comment]
If you need more help with Nyarch or linux in general you can ask in the support Telegram group or in the discord server
