### ISSUE TITLE
Delete nvidia ISO

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [NyarchLinux/NyarchLinux#25]
At the moment, Nvidia ISO does not work correctly since the module is missing from mkinitcpio

**Comment by FrancescoCaracciolo** [comment]
Nvidia ISO won't be provided anymore, however if there are complains and issues, you can sumbit them here

**Comment by ElryDeveloper** [comment]
I would say Nvidia users could install the Nvidia drivers themselfs, it would be nice if the installer could detect Nvidia Gpus and automatically doe that for the user, but if thats too much hassle i would just let them do it themselfs.

**Comment by FrancescoCaracciolo** [comment]
> I would say Nvidia users could install the Nvidia drivers themselfs, it would be nice if the installer could detect Nvidia Gpus and automatically download and install that for the user, but if thats too much hassle i would just let them do it themselfs.

If someone made a reliable nvidia install script, I could add it on Nyarch Script but I can't find any.

**Comment by ElryDeveloper** [comment]
> > I would say Nvidia users could install the Nvidia drivers themselfs, it would be nice if the installer could detect Nvidia Gpus and automatically download and install that for the user, but if thats too much hassle i would just let them do it themselfs.
> 
> If someone made a reliable nvidia install script, I could add it on Nyarch Script but I can't find any.

I know that EndavourOS has an thing that it detects if you use Nvidia and automatically Installs the correct driver, maybe going trough that install script and "lending" the Nvidia parts could be useful ^^

But as said in my other Issue, im very bad at Bash Scripts so besides giving you and idea about where to look i cant really help you in that regard.

**Comment by FrancescoCaracciolo** [comment]
Nvidia ISO is back
