### ISSUE TITLE
Nyarch Gnome broke?

### ISSUE THREAD

**Issue by DawnAkuuu** [NyarchLinux/NyarchLinux#27]
Heyo! So here's the issue I have,
I have a fresh Nyarch install on a regular intel system with no nvidia graphics card (non nvidia version) and after installation windows would have a weird ghosting effect where they would open but not show up. 

- I would have to move them to another tab view in gnome and then they would work but when I closed them they wouldn't close either but they also weren't interactive.
- I saw there were 665 updates so I updated to see if it would fix it but now when I click the application bar it kinda just stops working. 

Any way I can fix this issue? Lmk if more info is needed too
(BTW I'm pretty new to arch and linux systems in general but I do have a little bit of knowledge from a previous arch system)

**Comment by DawnAkuuu** [comment]
> Nyarch ISO is pretty much broken at the moment. Wait for the next update since it is a matter of days and it brings many improvements

lmao thanks for letting me know! Can't wait to get the new version

**Comment by FrancescoCaracciolo** [comment]
Closing the issue since the new version has been released and the issue solved
