### ISSUE TITLE
I just wanna ask whats the nyarch live boot password?

### ISSUE THREAD

**Issue by toxicfox2491** [NyarchLinux/NyarchLinux#3]
I wanna install nyarch in a VM and it put me to the live session login screen

**Comment by toxicfox2491** [comment]
nvm sorry lol! I found it out, I tried ithe ezarcher passwords before and it didnt work so I thought Id ask

**Comment by mekb-turtle** [comment]
what is the password

**Comment by monkeboi9** [comment]
the password is live
