### ISSUE TITLE
How to build iso?

### ISSUE THREAD

**Issue by Magi3r** [NyarchLinux/NyarchLinux#30]
It would be helpful for contributions to be able to build the iso for testing before submitting the changes. Can you provide a little guide on that in the Readme or in Contribution.md?

**Comment by FrancescoCaracciolo** [comment]
https://github.com/NyarchLinux/NyarchLinux/blob/main/Gnome/BUILDING.md

**Comment by Magi3r** [comment]
Oh, I didn't notice that file. How about mentioning it in the readme, because the BUILDING.md is not in the project root?

**Comment by FrancescoCaracciolo** [comment]
It is not in the project root because building instrctions might be different between different spins, as in theory this repo should contain every spin.
Though it should be directly linked in the root CONTRIBUTING.md
