### ISSUE TITLE
Can't install Nyarch in Dual boot

### ISSUE THREAD

**Issue by elblorenz32** [NyarchLinux/NyarchLinux#39]
(sorry, pressed enter too early... (somehow submitted it and opened a new window))

Hi, I have tried to install Nyarch from the ISO (put on a USB stick via Rufus) and it always fails with the message 
"Failed to unpack image /run/archiso/x86_64/airootfs.sfs 
Details: rsync failed with error code 11."

I know that unlike issue #12 , secure boot is turned off and that I'm giving it a ~14GB Partition of unassigned disc space

Addition: Speaking of Disk space, the Disk Tool tells me that the assigned partition seems to be full (Size: 14GB - 18MB free (99,9% full)) how large is that installation supposed to be?

**Comment by FrancescoCaracciolo** [comment]
You can, explain better your problem

**Comment by elblorenz32** [comment]
Alright, I have updated it

**Comment by FrancescoCaracciolo** [comment]
Give it at least 20GB

**Comment by elblorenz32** [comment]
Okay, I recommend 30GB, I threw a 500GB drive at it and it ate ~25GB of that (It's an HDD so it's not the quickest but it works now, thx!)
