### ISSUE TITLE
Not working with Ventoy

### ISSUE THREAD

**Issue by OkabeZeroLink** [NyarchLinux/NyarchLinux#40]
When I tried to install with Ventoy in UEFI mode, the log gave back something about syntax error then prompt me to press a key, which takes me back to the Ventoy screen. With legacy mode, the log clearly state that something is missing (Can't remember what it is, but it's there), then prompt me to press a key, which restart my laptop

**Comment by OkabeZeroLink** [comment]
Also, secure boot is disabled (or rather, not exist yet on ASUS X44H)

**Comment by FrancescoCaracciolo** [comment]
Is your computer BIOS or UEFI?

**Comment by OkabeZeroLink** [comment]
UEFI, I guess. I installed Mint and Arch using the UEFI mode of the flash drive. Though the BIOS itself seems like legacy BIOS. I have no idea how this works

**Comment by OkabeZeroLink** [comment]
Also, booting in BIOS+normal mode in Ventoy just now, it says that can't load ldlinux.c32

**Comment by FrancescoCaracciolo** [comment]
Ventoy should work fine with Nyarch, I don't know what issue are you getting. Maybe you should try flashing the ISO on an USB

**Comment by OkabeZeroLink** [comment]
Just noticed something when compared Arch with Nyarch ISO (Done on Mint):
- The file manager automatically recognize Arch as a bootable media type, while with Nyarch it doesn't say anything
- The ldlinux.c32 properties in Arch and Nyarch is quite different. In Arch it's recognized as a program - application/x-executable while the Nyarch one is recognized as a binary - application/octet-stream. Virtually every .c32 files properties in Nyarch and Arch are like what I described just now
Probably worth it to keep it in mind

**Comment by OkabeZeroLink** [comment]
Just redownload from SourceForge, and the difference that I said above just gone. Is the version from Nyarch server just different from the SourceForge one?

**Comment by FrancescoCaracciolo** [comment]
No, they are totally the same. Maybe the download was corrupted?

**Comment by OkabeZeroLink** [comment]
Yep, it was definitely corrupted. Sorry to bother
