### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vs66388** [NyarchLinux/NyarchLinux#9]
can you make a guide on how to build your own custom version of linux i mean if you go eww with a window manager like awesome it will be a full blown desktop which will be fraction in size i am just suggesting ang if i know how to cause i mean i dont have place to hold pacakges so a how to guide will be helpfull and i will work under your name i dont know how to reach you so here i created an issue so you can  notice me thank you for your time and tatakae dattebayo !!!!! 106

**Comment by FrancescoCaracciolo** [comment]
Hello, we have a bit of explaination in our [BUILDING.md](https://github.com/NyarchLinux/NyarchLinux/blob/main/Gnome/BUILDING.md)

If you want to contact us and help or just ask for support, we have a Telegram group: https://t.me/nyarchlinuxgroup
